/*
 * JS for nuevo_destino generated by Appery.io
 *
 */

Appery.getProjectGUID = function() {
    return '363c2cb1-4b4e-48f1-9c3d-1f8e2d3efea5';
}

function navigateTo(outcome, useAjax) {
    Appery.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Appery.adjustContentHeight();
}

function adjustContentHeightWithPadding() {
    Appery.adjustContentHeightWithPadding();
}

function setDetailContent(pageUrl) {
    Appery.setDetailContent(pageUrl);
}

Appery.AppPages = [{
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "mis_destinos",
    "location": "mis_destinos.html"
}, {
    "name": "nuevo_destino",
    "location": "nuevo_destino.html"
}];

nuevo_destino_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel_15': 'nuevo_destino_mobilelabel_15',
        'donde': 'donde',
        'mobilelabel_16': 'nuevo_destino_mobilelabel_16',
        'mobileselectmenu_23': 'nuevo_destino_mobileselectmenu_23',
        'mobileselectmenuitem_24': 'nuevo_destino_mobileselectmenuitem_24',
        'spacer_32': 'nuevo_destino_spacer_32',
        'mobilecheckboxgroup_27': 'nuevo_destino_mobilecheckboxgroup_27',
        'mobilecheckbox_28': 'nuevo_destino_mobilecheckbox_28',
        'mobilebutton_25': 'nuevo_destino_mobilebutton_25'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role=footer]").css("bottom", "-36px");
    }

    Appery.CurrentScreen = 'nuevo_destino';

    /*
     * Nonvisual components
     */
    var datasources = [];

    /*
     * Events and handlers
     */

    // Before Show
    nuevo_destino_beforeshow = function() {
        Appery.CurrentScreen = "nuevo_destino";
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }

    // On Load
    screen_868C_onLoad = nuevo_destino_onLoad = function() {
        screen_868C_elementsExtraJS();
		
		
        // TODO fire device events only if necessary (with JS logic)
        nuevo_destino_windowEvents();
        screen_868C_elementsEvents();
        nuevo_destino_deviceEvents();
        

    }

    // screen window events
    screen_868C_windowEvents = nuevo_destino_windowEvents = function() {
        $('#nuevo_destino').bind('pageshow orientationchange', function() {
            adjustContentHeightWithPadding();
        });

    }

    // device events
    nuevo_destino_deviceEvents = function() {
	
        document.addEventListener("deviceready", function() {
        	alert("jho");
        	var Xdestino = null;
			var Ydestino = null;
			var ac = new usig.AutoCompleter('donde', {
	       		rootUrl: '',
	       		/*skin: 'usig4',*/
	       		onReady: function() {
	       			$('#donde').val('').focus();
	       		},
	       		afterSelection: function(option) {
	           		if (option instanceof usig.Direccion || option instanceof usig.inventario.Objeto) {
	           			//$('#donde').val('');
	           		  	$('#borrar').show();
	           		  	var miGeoCoder = new usig.GeoCoder;
	           		  	
	           		  	miGeoCoder.geoCodificarDireccion(option, function(punto){ 
							$.getJSON("http://ws.usig.buenosaires.gob.ar/rest/convertir_coordenadas?x="+punto.getX()+"&y="+punto.getY()+"&output=lonlat", function(data){
								Xdestino=data.resultado.x;
								Ydestino=data.resultado.y;
									$('#x').html(data.resultado.x);
	           		  				$('#y').html(data.resultado.y);
							});
							
						}, function(){ alert("fuck");});
	           		  	
	           		}
	       		}
	       	});
	        
        });
    }

    // screen elements extra js
    screen_868C_elementsExtraJS = nuevo_destino_elementsExtraJS = function() {
        // screen (nuevo_destino) extra code

        /* mobileselectmenu_23 */

        $("#nuevo_destino_mobileselectmenu_23").parent().find("a.ui-btn").attr("tabindex", "9");

    }

    // screen elements handler
    screen_868C_elementsEvents = nuevo_destino_elementsEvents = function() {

        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });

    }

    $("#nuevo_destino").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        nuevo_destino_beforeshow();
    });

    if (runBeforeShow) {
        nuevo_destino_beforeshow();
    } else {
        nuevo_destino_onLoad();
    }

}

$("#nuevo_destino").die("pageinit").live("pageinit", function(event, ui) {
    Appery.processSelectMenu($(this));
    nuevo_destino_js();
});